-- MySQL Script generated by MySQL Workbench
-- Wed May 19 22:39:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema freedbtech_LibraryManager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema freedbtech_LibraryManager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `freedbtech_LibraryManager` DEFAULT CHARACTER SET utf8 ;
USE `freedbtech_LibraryManager` ;

-- -----------------------------------------------------
-- Table `freedbtech_LibraryManager`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freedbtech_LibraryManager`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(60) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freedbtech_LibraryManager`.`Bookshelf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freedbtech_LibraryManager`.`Bookshelf` (
  `idBookshelf` INT NOT NULL AUTO_INCREMENT,
  `rowB` INT NULL,
  `columnB` INT NULL,
  `name` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idBookshelf`),
  INDEX `fk_Bookshelf_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Bookshelf_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `freedbtech_LibraryManager`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freedbtech_LibraryManager`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freedbtech_LibraryManager`.`Book` (
  `idBook` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `pages` INT NULL,
  `Bookshelf_idBookshelf` INT NOT NULL,
  `toRead` TINYINT NULL,
  `stars` INT NULL,
  `photo` VARCHAR(250) NULL,
  PRIMARY KEY (`idBook`),
  INDEX `fk_Book_Bookshelf1_idx` (`Bookshelf_idBookshelf` ASC),
  CONSTRAINT `fk_Book_Bookshelf1`
    FOREIGN KEY (`Bookshelf_idBookshelf`)
    REFERENCES `freedbtech_LibraryManager`.`Bookshelf` (`idBookshelf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `freedbtech_LibraryManager`.`Reminder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `freedbtech_LibraryManager`.`Reminder` (
  `idReminder` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `completed` TINYINT NULL,
  `User_idUser` INT NOT NULL,
  `Book_idBook` INT NOT NULL,
  PRIMARY KEY (`idReminder`),
  INDEX `fk_Reminder_User1_idx` (`User_idUser` ASC),
  INDEX `fk_Reminder_Book1_idx` (`Book_idBook` ASC),
  CONSTRAINT `fk_Reminder_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `freedbtech_LibraryManager`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reminder_Book1`
    FOREIGN KEY (`Book_idBook`)
    REFERENCES `freedbtech_LibraryManager`.`Book` (`idBook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
